server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: announcement-service
          uri: lb://announcement-service
          predicates:
          - Path=/announcement/**
        - id: announcement-service
          uri: lb://announcement-service
          predicates:
            - Path=/announcement/**